name: GitHub Actions pipeline for Fashion MNIST classification model
on:
  push:
    branches:
    - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-bookworm
    steps:
    - name: Install pip dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the unit tests
      run: |
        pytest -v
