name: GitHub Actions pipeline for Fashion MNIST classification model
on:
  push:
    branches:
    - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install pip dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the unit tests
      run: |
        pytest -v
